export type BuildNote = {
  label: string;
  value: string;
};

export async function loadBuildNotes(environment: string): Promise<BuildNote[]> {
  return Promise.resolve([
    {
      label: 'HTML shell',
      value: 'Generated by HtmlWebpackPlugin during the webpack build.',
    },
    {
      label: 'Static file',
      value: 'Copied from public/robots.txt into dist by CopyWebpackPlugin.',
    },
    {
      label: 'Environment',
      value: `Loaded from .env.${environment === 'Production Control Room' ? 'production' : 'development'} and injected through DefinePlugin.`,
    },
  ]);
}